name: Generate SBOMs

on:
  workflow_dispatch:
  pull_request:

jobs:
  main:
    name: Generate SBOMs
    runs-on: [self-hosted, integration]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: bash generate-sboms.bash

      - uses: actions/upload-artifact@v4
        with:
          path: dist
          name: zenoh-sboms
